"""Analytics modules."""

from dumb_money.analytics.company import (
    STANDARD_MOVING_AVERAGES,
    STANDARD_RETURN_WINDOWS,
    build_benchmark_comparison,
    build_drawdown_series,
    build_fundamentals_summary,
    build_indexed_price_series,
    build_moving_average_series,
    build_peer_summary_stats,
    build_peer_return_comparison,
    build_peer_return_summary_stats,
    build_peer_valuation_comparison,
    build_trailing_return_comparison,
    calculate_return_windows,
    calculate_risk_metrics,
    calculate_trend_metrics,
    prepare_price_history,
)
from dumb_money.analytics.portfolio import (
    build_candidate_fit_summary,
    build_portfolio_benchmark_comparison,
    build_portfolio_concentration_metrics,
    build_portfolio_exposure,
    build_watchlist_decision_table,
    enrich_portfolio_holdings,
)
from dumb_money.analytics.scorecard import (
    DEFAULT_PRIMARY_BENCHMARK,
    DEFAULT_SECTOR_BENCHMARK_MAP,
    CompanyScorecard,
    build_company_scorecard,
    resolve_secondary_benchmark,
)

__all__ = [
    "CompanyScorecard",
    "DEFAULT_PRIMARY_BENCHMARK",
    "DEFAULT_SECTOR_BENCHMARK_MAP",
    "STANDARD_MOVING_AVERAGES",
    "STANDARD_RETURN_WINDOWS",
    "build_benchmark_comparison",
    "build_drawdown_series",
    "build_company_scorecard",
    "build_candidate_fit_summary",
    "build_portfolio_benchmark_comparison",
    "build_fundamentals_summary",
    "build_indexed_price_series",
    "build_moving_average_series",
    "build_portfolio_concentration_metrics",
    "build_portfolio_exposure",
    "build_watchlist_decision_table",
    "build_peer_summary_stats",
    "build_peer_return_comparison",
    "build_peer_return_summary_stats",
    "build_peer_valuation_comparison",
    "build_trailing_return_comparison",
    "calculate_return_windows",
    "calculate_risk_metrics",
    "calculate_trend_metrics",
    "enrich_portfolio_holdings",
    "prepare_price_history",
    "resolve_secondary_benchmark",
]
